### ISSUE TITLE
off-by-1 error in method 'franz.openrdf.model.value.URI.split()'

### ISSUE THREAD

**Issue by fventuri-availity** [franzinc/agraph-python#10]
This line in the method 'franz.openrdf.model.value.URI.split()' adds 1 to the position of the split resulting in incorrect results:
https://github.com/franzinc/agraph-python/blob/e51f91af2b17d783fc71f6316e5d88035681369a/src/franz/openrdf/model/value.py#L165

The correct line should be:
return self.uri[:pos], self.uri[pos:]

Also I see in several places in the file those methods use sometimes 'self.getURI()' and other times 'self.uri' - it would be nice if they were consistent, one way or the other.

Regards,
Franco Venturi

**Comment by jkftiger348** [comment]
Thank you for your report.  The bug has been fixed in 101.0.5

**Comment by fventuri-availity** [comment]
Thanks John.

Franco
